[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.38"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "0.10.1"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/twinj/uuid"
  version = "1.0.0"

[prune]
  go-tests = true
  unused-packages = true
